version: "3.2"

services:
  app:
    build:
      context: aplicacao/
      dockerfile: Dockerfile
    volumes:
      - ./aplicacao:/app
    ports:
      - 3000:3000
    networks:
      - app
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    command: -p 5432
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app
      
volumes:
  postgres_data:

networks:
  app:
    driver: bridge