name: App-CI

on:
  workflow_call:  
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run app
        run: docker-compose up -d

  lint:
    runs-on: ubuntu-latest
    needs: [app]
    steps:
      - uses: actions/checkout@v3
      - name: run lint
        run: docker-compose run app bash -c "gem install rubocop; rubocop --fail-level F"

  test:
    runs-on: ubuntu-latest
    needs: [app]
    steps:
      - uses: actions/checkout@v3
      - name: run tests
        run: docker-compose run app bash -c "rails db:reset; rspec"
